kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: promote-data-card
spec:
  host: mlops-router-demo-2.apps.cluster-497z4.497z4.sandbox2736.opentlc.com
  path: /promote-data-card
  to:
    kind: Service
    name: el-promote-listener
    weight: 100
  port:
    targetPort: http-listener
  wildcardPolicy: None
