apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: promote-binding
spec:
  params:
    - name: data_card
      value: $(body.DataCard)
    - name: bucket
      value: $(body.Bucket)
    - name: directory
      value: $(body.Directory)
    - name: s3_url
      value: $(body.S3Url)
    - name: access_key
      value: $(body.AccessKey)
    - name: secret_key
      value: $(body.SecretKey)
