apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: dry-run
    serving.knative.openshift.io/enablePassthrough: "true"
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
  labels:
    opendatahub.io/dashboard: "true"
  name: dry-run
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: vLLM
      name: ""
      resources:
        limits:
          cpu: "10"
          memory: 20Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "6"
          memory: 16Gi
          nvidia.com/gpu: "1"
      runtime: dry-run-runtime
      storage:
        key: model-bucket
        path: granite-7b-instruct/
    tolerations:
    - effect: NoSchedule
      key: nvidia.com/gpu
      operator: Exists
