kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: promote-data-card
spec:
  host: mlops-router-demo-3.apps.cluster-4ghn9.4ghn9.sandbox2431.opentlc.com
  path: /promote-data-card
  to:
    kind: Service
    name: el-promote-listener
    weight: 100
  port:
    targetPort: http-listener
  wildcardPolicy: None
