apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: upload-data-card
spec:
  params:
    - name: payload_body
      type: string
    - name: event_name
      type: string
    - name: key
      type: string
    - name: records
      type: string
    - name: endpoint
      type: string
  tasks:
    - name: upload-data-card
      params:
        - name: payload_body
          value: $(params.payload_body)
        - name: event_name
          value: $(params.event_name)
        - name: key
          value: $(params.key)
        - name: records
          value: $(params.records)
        - name: endpoint
          value: $(params.endpoint)
      taskRef:
        kind: Task
        name: upload-data-card
