apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: build-model-listener
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: build-model-binding
      name: build-model-trigger
      template:
        ref: build-model-template