apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: build-model-binding
spec:
  params:
    - name: data_card
      value: $(body.DataCard)
    - name: model_request
      value: $(body.ModelRequest)
    - name: model_location
      value: $(body.ModelLocation)
    - name: model_card_name
      value: $(body.ModelCardName)
    - name: metadata
      value: $(body.Metadata)
