apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'kustomize-app'
spec:
  project: default
  source:
    repoURL: https://github.com/MLOps-OpenAPI/incubator-demos.git
    path: demo-3/template/kustomize/deploy-model
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # syncOptions:
    #   - CreateNamespace=true
