apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: minio-binding
spec:
  params:
    - name: payload_body
      value: $(body)
    - name: event_name
      value: $(body.EventName)
    - name: key
      value: '$(body.Records[0].s3.bucket.name)-$(body.Records[0].responseElements.x-minio-deployment-id)'
    - name: endpoint
      value: '$(body.Records[0].responseElements.x-minio-origin-endpoint)'
    - name: records
      value: $(body.Records)
