apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: deploy-model-listener
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: deploy-model-binding
      name: deploy-model-trigger
      template:
        ref: deploy-model-template