---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: replace-vars
spec:
  params:
  - default: "4.18"
    description: The OpenShift Version to use
    name: VERSION
    type: string
  - default: ""
    description: The S3 URL Endpoint
    name: bucket-endpoint
    type: string
  - default: ""
    description: The S3 Bucket Name
    name: bucket-name
    type: string
  - default: ""
    description: The Model path inside of the S3 Bucket
    name: bucket-path
    type: string
  - default: ""
    description: The S3 secret name
    name: display-name
    type: string
  - default: ""
    description: The InferenceService name
    name: inference-name
    type: string
  - default: ""
    description: The namespace where everything is gonna be
    name: namespace
    type: string
  - default: ""
    description: The ServingRuntime name
    name: serving-name
    type: string
  steps:
  - computeResources: {}
    image: quay.io/openshift/origin-cli:$(params.VERSION)
    name: replace-vars
    script: |
      #!/usr/bin/env bash

      set -x

      ### Create the new directory with the manifests from template
      export DATE_SUFFIX=`date -u +%+4Y%m%d-%H%M%S-%N` ### eg: 20250402-112718-505481385
      export MANIFEST_DIR=test-${DATE_SUFFIX}
      echo "${MANIFEST_DIR}" > "$(results.manifests-dir.path)"

      cd $(workspaces.output.path)/
      cp -a template model_serving/${MANIFEST_DIR}
      cd model_serving/${MANIFEST_DIR}

      ### Read keys from s3-creds
      export S3_ACCESS_KEY_ID=`cat $(workspaces.s3-creds.path)/S3_ACCESS_KEY_ID`
      export S3_SECRET_ACCESS_KEY=`cat $(workspaces.s3-creds.path)/S3_SECRET_ACCESS_KEY`

      ### Substitute CHANGEME vars with actual values
      ### Using hash sign (#) on endpoint and path
      ### as they contain / in the value, messing up the substitution

      sed -i "s/REPLACE_ACCESS_KEY/${S3_ACCESS_KEY_ID}/g" *.yaml
      sed -i "s/REPLACE_SECRET_KEY/${S3_SECRET_ACCESS_KEY}/g" *.yaml
      sed -i "s/REPLACE_BUCKET_NAME/$(params.bucket-name)/g" *.yaml
      sed -i "s#REPLACE_BUCKET_ENDPOINT#$(params.bucket-endpoint)#g" *.yaml
      sed -i "s#REPLACE_BUCKET_PATH#$(params.bucket-path)#g" *.yaml
      sed -i "s/REPLACE_DISPLAY_NAME/$(params.display-name)/g" *.yaml
      sed -i "s/REPLACE_INFERENCE_NAME/$(params.inference-name)/g" *.yaml
      sed -i "s/REPLACE_NAMESPACE/$(params.namespace)/g" *.yaml
      sed -i "s/REPLACE_SERVING_NAME/$(params.serving-name)/g" *.yaml

      ### Apply changes
      oc apply -k .

      ### Print out the route to hit
      echo "Waiting for the InferenceService to deploy..."
      oc wait --for=jsonpath='{.status.url}' --timeout=3600s inferenceservice/$(params.inference-name)

      echo "InferenceService deployed and available: "
      oc get inferenceservice $(params.inference-name) -o jsonpath='{.status.url}' | tee "$(results.inference-route.path)"

      ### Get the actual secret instead of the plain text values from the template
      oc get secret -n $(params.namespace) $(params.display-name) -o yaml > s3-bucket.yaml
  workspaces:
  - name: output
  - name: s3-creds
  results:
  - description: The exposed route that points to the newly created InferenceService
    name: inference-route
    type: string
  - description: The name of the edited manifests
    name: manifests-dir
    type: string
