apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: minio-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: minio-binding
      name: minio-trigger
      template:
        ref: minio-template

