apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  annotations:
    triggers.tekton.dev/old-escape-quotes: 'true'
  name: update-model-location-template
spec:
  params:
    - name: model_card
    - name: model_pull_location
    - name: bucket
    - name: s3_url
    - name: access_key
    - name: secret_key
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: upload-data-card-run-
      spec:
        params:
          - name: file_name
            value: $(tt.params.model_card)
          - name: model_pull_location
            value: $(tt.params.model_pull_location)
          - name: bucket_name
            value: $(tt.params.bucket)
          - name: endpoint_url
            value: $(tt.params.s3_url)
          - name: aws_access_key_id
            value: $(tt.params.access_key)
          - name: aws_secret_access_key
            value: $(tt.params.secret_key)
        pipelineRef:
          name: update-model-location
