kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: update-model-pull-location
spec:
  host: mlops-router-demo.apps.cluster-vtmgm.vtmgm.sandbox441.opentlc.com
  path: /update-model-pull-location
  to:
    kind: Service
    name: el-update-model-location-listener
    weight: 100
  port:
    targetPort: http-listener
  wildcardPolicy: None
