apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: update-model-pull-location
spec:
  rules:
  - http:
      paths:
      - path: /update-model-pull-location
        pathType: Prefix
        backend:
          service:
            name: el-update-model-location-listener
            port:
              number: 8080
