apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: update-model-location-binding
spec:
  params:
    - name: model_card
      value: $(body.ModelCard)
    - name: model_pull_location
      value: $(body.ModelPullLocation)
    - name: bucket
      value: $(body.Bucket)
    - name: s3_url
      value: $(body.S3Url)
    - name: access_key
      value: $(body.AccessKey)
    - name: secret_key
      value: $(body.SecretKey)
