apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: request-model
spec:
  params:
    - name: model_request
      type: string
    - name: algorithm
      type: string
    - name: results
      type: string
    - name: comments
      type: string
      default: ''
  tasks:
    - name: request-model
      params:
        - name: model_request
          value: $(params.model_request)
        - name: algorithm
          value: $(params.algorithm)
        - name: results
          value: $(params.results)
        - name: comments
          value: $(params.comments)
      taskRef:
        kind: Task
        name: request-model
