kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: request-model
spec:
  host: mlops-router-demo.apps.cluster-vtmgm.vtmgm.sandbox441.opentlc.com
  path: /request-model
  to:
    kind: Service
    name: el-request-model-listener
    weight: 100
  port:
    targetPort: http-listener
  wildcardPolicy: None