kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: data-intake
spec:
  host: mlops-router-demo-2.apps.cluster-497z4.497z4.sandbox2736.opentlc.com
  path: /data-intake
  to:
    kind: Service
    name: el-s3-listener
    weight: 100
  port:
    targetPort: http-listener
  wildcardPolicy: None
