apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'flask-router'
spec:
  project: default
  source:
    repoURL: https://github.com/MLOps-OpenAPI/incubator-demos.git
    path: python/flask-router/manifests
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true