apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: promote-data-card
spec:
  rules:
  - http:
      paths:
      - path: /promote-data-card
        pathType: Prefix
        backend:
          service:
            name: el-promote-listener
            port:
              number: 8080
