openapi: 3.0.3
info:
  title: Data Ingestion
  description: Processes related to acquiring and importing data. Primary Personas are Data Engineers, Platform Engineers
  version: 1.0.0
paths:
  /data-intake:
    post:
      summary: Data Intake
      description: >
        Creates a new data card, or updates one if it exsists
      tags:
        - Data Ingestion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                DataCard:
                  type: string
                  example: "test3"
                Bucket:
                  type: string
                  example: "anthony-test-bucket"
                S3Url:
                  type: string
                  format: uri
                  example: "https://minio-api-minio.apps.cluster-4ghn9.4ghn9.sandbox2431.opentlc.com"
                AccessKey:
                  type: string
                SecretKey:
                  type: string
                path:
                  type: string
                  example: "/test_folder"
                  default: "/"
              required:
                - DataCard
                - Bucket
                - S3Url
                - AccessKey
                - SecretKey
      responses:
        "200":
          description: Successful data intake.
          content:
            application/json:
              schema:
                type: object
                properties:
                  eventListener:
                    type: string
                  namespace:
                    type: string
                  eventListenerUID:
                    type: string
                  eventID:
                    type: string
        '400':
          description: Invalid input data.
        '500':
          description: Internal server error.
